server:
  port: 8181

spring:
  application:
    name: users

k8sPet:
  services:
    orders:
      url: http://orders/orders

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka